// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_welcome_to_high_calorie_tube = "CgkIp-C1lr0REAIQCA"; // <GPGSID>
        public const string achievement_reach_to_1000_m = "CgkIp-C1lr0REAIQDA"; // <GPGSID>
        public const string achievement_reach_to_2000_m = "CgkIp-C1lr0REAIQBA"; // <GPGSID>
        public const string achievement_gather_100_pizza = "CgkIp-C1lr0REAIQCg"; // <GPGSID>
        public const string leaderboard_high_score = "CgkIp-C1lr0REAIQAQ"; // <GPGSID>
        public const string leaderboard_gathered_burger = "CgkIp-C1lr0REAIQCw"; // <GPGSID>
        public const string achievement_gather_1000_burgers = "CgkIp-C1lr0REAIQCQ"; // <GPGSID>
        public const string achievement_reach_to_5000_m = "CgkIp-C1lr0REAIQBg"; // <GPGSID>
        public const string achievement_run_to_10000_m = "CgkIp-C1lr0REAIQBw"; // <GPGSID>
        public const string achievement_gather_200_pizza = "CgkIp-C1lr0REAIQDw"; // <GPGSID>
        public const string achievement_gather_50_pizza = "CgkIp-C1lr0REAIQEA"; // <GPGSID>
        public const string achievement_gather_500_burgers = "CgkIp-C1lr0REAIQDQ"; // <GPGSID>
        public const string achievement_gather_250_burgers = "CgkIp-C1lr0REAIQDg"; // <GPGSID>

}

